### ISSUE TITLE
Multiple labels within a uitableview cell don't show right color

### ISSUE THREAD

**Issue by nithinreddy** [hsusmita/ResponsiveLabel#18]
I've multiple tables within a uitableview row. But a few hashtags get highlighted, and few don't. As i scroll up and come to the cell again, it changes randomly. 
Can you please check this case?

For some reason, the behavior of ResponsiveLabel in UITableView isn't consistent.

**Comment by hsusmita** [comment]
@nithinreddy can you confirm that two hashtags have space between them? Currently it cannot recognise the 2nd hashtag if there is no space between two hashtags.

I will look into scrolling issue.

**Comment by nithinreddy** [comment]
Yes, there is a space. Its basically 2 different labels.

Also, there is an issue that if the hashtag is the end of the label, it
won't recognize it. So I'm appending spaces to each and every label.

**Comment by hsusmita** [comment]
@nithinreddy When you append space in the end, does it work for scrolling also?

**Comment by nithinreddy** [comment]
No, the scroll issue still persists

**Comment by nithinreddy** [comment]
See the images image and you know what I mean. It happened when I scrolled back in. In the first image, #sogood wasn't detected. When I scrolled down and then up, one was detected, and one was not.

<img width="347" alt="screen shot 2015-09-23 at 1 24 53 pm" src="https://cloud.githubusercontent.com/assets/3472256/10040134/910e7ca4-61f6-11e5-8bf7-9bd2b47a509e.png">
<img width="340" alt="screen shot 2015-09-23 at 1 25 01 pm" src="https://cloud.githubusercontent.com/assets/3472256/10040133/910a8a68-61f6-11e5-8561-374f4ffa465a.png">

**Comment by nithinreddy** [comment]
Hi, did you get a chance to check this?

**Comment by hsusmita** [comment]
@nithinreddy hey I will update EOD.

**Comment by hsusmita** [comment]
@nithinreddy I have pushed latest code in bugfixes branch. Please do your tests and let me know. Then I will merge with master.

**Comment by nithinreddy** [comment]
Just checked it and it still appears :( 

See the screenshots below please.

<img width="360" alt="screen shot 2015-09-26 at 8 30 10 am" src="https://cloud.githubusercontent.com/assets/3472256/10115539/e6c19b66-6428-11e5-8d04-d4012e61de12.png">
<img width="365" alt="screen shot 2015-09-26 at 8 30 00 am" src="https://cloud.githubusercontent.com/assets/3472256/10115540/e6ef25fe-6428-11e5-8662-2fa7541c94e1.png">

Thanks a lot for your time.

**Comment by hsusmita** [comment]
@nithinreddy Can you provide me sample project isolating the problem? May be I can experiment on conditions which I might have missed.

**Comment by patheticcockroach** [comment]
Hi, I have a similar issue with multiline URLs when they are in table cells, in a big enough table (say, vertical table with 20 cells where each cell takes roughly 25% of the screen). One-line URLs are always detected, multiline URLs are more random, and just like OP it changes when I scroll up and down.
After a bit more testing, in iOS Simulator:
- on iPhone 5s, multiline URL seems to always failed provided the table is big enough
- on iPhone 6s Plus, it seems that multiline URL always succeed if I scroll slowly and always fail if I scroll very fast

The code I use to handle the responsive label is below:

```
cell.lblPostDescriptionResponsive.userInteractionEnabled = YES;
    PatternTapResponder urlTapAction = ^(NSString *tappedString) {
        NSLog(@"URL Tapped = %@",tappedString);
    };
    [cell.lblPostDescriptionResponsive enableURLDetectionWithAttributes:
         @{NSForegroundColorAttributeName:self.meltingBlue,
           NSUnderlineStyleAttributeName:[NSNumber numberWithInt:1],
           RLTapResponderAttributeName:urlTapAction}];
    NSString *cellText=@"";
    [cellText = [replies [indexPath.row] valueForKey:TXT]
    stringByConvertingHTMLToPlainText];
    [cell.lblPostDescriptionResponsive setText:cellText
    withTruncation:NO];
```

**Comment by Saulenco** [comment]
Hi i have the same issue , one multiline label with 2 string for detection and only one worked. The only solution that i had is to refresh the tableView in viewDidAppear
